deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: /
  target-branch: gh-pages
  commit_message: "Deploy"
  on:
    branch: master
